FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openjdk-21-jdk && \
    apt-get clean

# Создаем директорию /app
RUN mkdir -p /app

# Копируем JAR-файл (убедитесь, что он существует в target/)
COPY target/social_network-0.0.1-SNAPSHOT.jar /app/app.jar

WORKDIR /app

CMD ["java", "-jar", "app.jar"]